# Generated by Django 5.0 on 2023-12-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("track", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="duration",
            field=models.IntegerField(),
        ),
    ]
