# Generated by Django 5.0 on 2023-12-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("track", "0003_alter_track_last_play"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="duration",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="track",
            name="last_play",
            field=models.DateTimeField(),
        ),
    ]
