# Generated by Django 5.0 on 2023-12-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("track", "0004_alter_track_duration_alter_track_last_play"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="duration",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="track",
            name="last_play",
            field=models.DateField(),
        ),
    ]
